package oops.object;


/*  Object class provides 11 methods
    * Public String toString(); to get string representation of an Object.to print object reference, toString() called
    * it returns classname@hashcode in hexadecimal form. All wrapper class & collection have to string overriden.
    * Public native int hashCode(); doesn't give address of object as we can override this. For every Object, a unique num generated by JVm
     Hash Set,Hash Table, Hash Map based on Hash Map. Search operation becomes easy (O(1)).
     If we use toString() method from Object class then it calls hashcode ()
    * Public boolean equals(Object o); reference comparision
    * protected native Object clone()throws CloneNotSupportedException
    * protected void finalize()throws Throwable -garbage collection
    * public final Class getClass() This method returns the runtime class of this object
    * public final void wait()throws InterruptedException
    * public final native void wait(long ms)throws InterruptedException
    * public final native void wait(long ms,int ns)throws InterruptedException
    * public final notify(long ms,int ns)
    * public final notifyAll()
    *
    * /
public class ObjectClass {
}
 */
